<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\RedisControlModel;

class Branch extends RedisControlModel
{
    protected $table = "branches";
    public $redisKeys = "_branches";

    //protected $fillable = ["company_id", "branch_name", "parent_branch", "is_grand_child", "email", "mobile", "address", "emergency_mobile"];
    protected $fillable = ["branch_name", "company_id", "parent_branch", "is_grand_child", "email", "mobile", "address", "emergency_mobile"];


    protected static function boot()
    {
        parent::boot();
         // TODO: Change the autogenerated stub
        $redisKeys = env("APP_NAME")."_".(new self())->table;

        static::saving(function ($model){

        });
        static::saved(function ($model){
            (new self())->updateOnChange();
        });

        static::retrieved(function ($model) use ($redisKeys){
            //$model->company_id =  $redisKeys;
        });
        static::created(function ($model){
            (new self())->updateOnChange();
        });
        static::updated(function ($model){
            (new self())->updateOnChange();
        });
        static::deleted(function ($model){
            (new self())->updateOnChange();
        });

    }


    /**
     * Scope a query to only include active users.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('isdelete', '0');
    }

    public function parent(){
        return $this->hasOne(Branch::class,'id','parent_branch');
    }
}
