<?php

namespace App;

use App\Helpers\RedisControlModel;
use Illuminate\Database\Eloquent\Model;

class Client extends RedisControlModel
{
    protected $table = "clients";

    protected $fillable = ["client_name", "contact_person", "mobile_no", "company_id", "branch_id", "code", "client_image", "code_converter", "personal_number"];


    protected static function boot()
    {
        parent::boot();
        // TODO: Change the autogenerated stub
        $redisKeys = env("APP_NAME")."_".(new self())->table;

        static::saving(function ($model){

        });
        static::saved(function ($model){
            (new self())->updateOnChange();
        });

        static::retrieved(function ($model) use ($redisKeys){
            //$model->company_id =  $redisKeys;
        });
        static::created(function ($model){
            (new self())->updateOnChange();
        });
        static::updated(function ($model){
            (new self())->updateOnChange();
        });
        static::deleted(function ($model){
            (new self())->updateOnChange();
        });

    }

}
